"""Add ShopDrink table

Revision ID: 22df3a56708d
Revises: 6b8879fc0223
Create Date: 2026-03-13 03:53:30.298311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22df3a56708d'
down_revision: Union[str, None] = '6b8879fc0223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_drinks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['coffee_shops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_drinks')
    # ### end Alembic commands ###
