"""Add signature and trending to shop_drinks

Revision ID: 74fb699fc630
Revises: 22df3a56708d
Create Date: 2026-03-13 04:00:51.690019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fb699fc630'
down_revision: Union[str, None] = '22df3a56708d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_drinks', sa.Column('is_signature', sa.Boolean(), nullable=True))
    op.add_column('shop_drinks', sa.Column('is_trending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_drinks', 'is_trending')
    op.drop_column('shop_drinks', 'is_signature')
    # ### end Alembic commands ###
