"""extend_shop_suggestions

Revision ID: a683468423a3
Revises: e3e7de79f7e5
Create Date: 2026-03-13 04:35:31.972971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a683468423a3'
down_revision: Union[str, None] = 'e3e7de79f7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_suggestions', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.add_column('shop_suggestions', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('shop_suggestions', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('shop_suggestions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('shop_suggestions', sa.Column('opening_hours', sa.String(length=100), nullable=True))
    op.add_column('shop_suggestions', sa.Column('price_range', sa.String(length=50), nullable=True))
    op.add_column('shop_suggestions', sa.Column('json_data', sa.Text(), nullable=True))
    op.add_column('shop_suggestions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('shop_suggestions', 'address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_foreign_key(None, 'shop_suggestions', 'coffee_shops', ['shop_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop_suggestions', type_='foreignkey')
    op.alter_column('shop_suggestions', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('shop_suggestions', 'updated_at')
    op.drop_column('shop_suggestions', 'json_data')
    op.drop_column('shop_suggestions', 'price_range')
    op.drop_column('shop_suggestions', 'opening_hours')
    op.drop_column('shop_suggestions', 'description')
    op.drop_column('shop_suggestions', 'image_url')
    op.drop_column('shop_suggestions', 'phone')
    op.drop_column('shop_suggestions', 'shop_id')
    # ### end Alembic commands ###
