"""Add category to shop_drinks

Revision ID: e3e7de79f7e5
Revises: 74fb699fc630
Create Date: 2026-03-13 04:08:55.708722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e7de79f7e5'
down_revision: Union[str, None] = '74fb699fc630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_drinks', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_drinks', 'category')
    # ### end Alembic commands ###
